#!/usr/bin/python

import roslib; roslib.load_manifest('joint_state_muxer')
import rospy
from sensor_msgs.msg import JointState
from urdf_parser_py.urdf import URDF
from math import pi

def get_param(name, value=None):
    private = "~%s" % name
    if rospy.has_param(private):
        return rospy.get_param(private)
    elif rospy.has_param(name):
        return rospy.get_param(name)
    else:
        return value

class JointStateMuxer():
    def __init__(self):
        description = get_param('robot_description')
        robot = URDF().parse_xml_string(description)
        self.free_joints = {}
        self.joint_list = [] # for maintaining the original order of the joints
        self.dependent_joints = get_param("dependent_joints", {})

        # Find all non-fixed joints
        for (jname, joint) in robot.joints.items():
            jtype = joint.joint_type
            if jtype == 'fixed':
                continue
            name = joint.name
            if jtype == 'continuous' or joint.limits is None:
                minval = -pi
                maxval = pi
            else:
                minval = joint.limits.lower
                maxval = joint.limits.upper

            if joint.mimic is not None:
                entry = {'parent': joint.mimic.joint_name }
                if joint.mimic.multiplier is not None:
                    entry['factor'] = joint.mimic.multiplier
                if joint.mimic.offset is not None:
                    entry['offset'] = joint.mimic.offset
                self.dependent_joints[name] = entry
                continue
            elif name in self.dependent_joints:
                continue
            elif minval > 0 or maxval < 0:
                zeroval = (maxval + minval)/2
            else:
                zeroval = 0

            joint = {'min':minval, 'max':maxval, 'zero':zeroval, 'position':zeroval, 'velocity':0}
            self.free_joints[name] = joint
            self.joint_list.append(name)

        source_list = get_param("source_list", [])
        self.sources = []
        for source in source_list:
            self.sources.append(rospy.Subscriber(source, JointState, self.source_cb))

        self.pub = rospy.Publisher('joint_states', JointState)

    def source_cb(self, msg):
        for i in range(len(msg.name)):
            name = msg.name[i]
            if name in self.free_joints:
                joint = self.free_joints[name]
                joint['position'] = msg.position[i]
                if len(msg.velocity) > i:
                    joint['velocity'] = msg.velocity[i]
                else:
                    joint['velocity'] = 0.0


    def loop(self):
        hz = get_param("rate", 50) # 50 Hz
        r = rospy.Rate(hz)

        # Publish Joint States
        while not rospy.is_shutdown():
            msg = JointState()
            msg.header.stamp = rospy.Time.now()

            # Add Free Joints
            for (name, joint) in self.free_joints.items():
                msg.name.append(str(name))
                msg.position.append(joint['position'])
                msg.velocity.append(joint['velocity'])

            # Add Dependent Joints
            for (name, param) in self.dependent_joints.items():
                parent = param['parent']
                baseval = self.free_joints[parent]['position']
                value = baseval * param.get('factor', 1)

                msg.name.append(str(name))
                msg.position.append(value)
                msg.velocity.append(0.0)

            self.pub.publish(msg)

            r.sleep()

if __name__ == '__main__':
    try:
        rospy.init_node('joint_state_muxer')
        jsp = JointStateMuxer()
        jsp.loop()

    except rospy.ROSInterruptException:
        pass
